### ISSUE TITLE
deepcopy-gen doesn't handle pointer-to-slice correctly

### ISSUE THREAD

**Issue by danwinship** [kubernetes/gengo#11]
If you have a struct with a pointer to a slice, eg:

```
Ports *[]NetworkPolicyPort `json:"ports,omitempty"`
```

(because you need to distinguish "field is not set" from "field is set to []") then deepcopy-gen generates incorrect code to copy it, resulting in:

```
../../apis/extensions/zz_generated.deepcopy.go:587: invalid argument *in (type *[]NetworkPolicyPort) for len
```

because it outputs code as though the field was a slice, not a pointer-to-slice. (Presumably pointer-to-map fields have the same problem.)

(kubernetes/kubernetes#25835 has more discussion of the use case.)

I don't have a simple reproducer, but, eg, changing NetworkPolicyIngressRule.Ports in kubernetes/pkg/apis/extensions/types.go from `[]NetworkPolicyPort` to `*[]NetworkPolicyPort` and regenerating stuff will trigger the error above.

**Comment by sttts** [comment]
This is fixed, compare https://github.com/kubernetes/gengo/blob/master/examples/deepcopy-gen/output_tests/pointer/doc.go#L26 for a test case.
