### ISSUE TITLE
Add plural rules to namer for words ending in 'o'

### ISSUE THREAD

**Issue by font** [kubernetes/gengo#126]
The `namer` package, specifically the method https://github.com/font/kubernetes/blob/91e7b4fd31fcd3d5f436da26c980becec37ceefe/vendor/k8s.io/gengo/namer/plural_namer.go#L54, does not contain any rules for words ending in `o`. See https://howtospell.co.uk/making-O-words-plural for more details.

**Comment by lavalamp** [comment]
That type should never have been added. Pluralizing words in code is a huge mistake 99.9% of the time.

Both deleting it and fixing it would be a backwards compatibility problem, unfortunately.
