### ISSUE TITLE
Support for JSONMap in CRDs

### ISSUE THREAD

**Issue by Kashomon** [kubernetes/gengo#128]
I have a CRD that I'm working on that is a wrapper around other objects, and so has the form

```go
type UnstructuredJSON map[string]interface{}

type MyMessage struct {
  Objects []UnstructuredJSON
}
```

`map[string]interface{}` doesn't translate well with DeepCopy:

```
*out = make([]UnstructuredJSON, len(*in))
for i := range *in {
	if (*in)[i] != nil {
		in, out := &(*in)[i], &(*out)[i]
		*out = make(UnstructuredJSON, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyinterface{}()
			}
		}
	}
}
```

`(*out)[key] = val.DeepCopyinterface{}()` is an error

I think some sort of UnstructuredJSON (called JSONMap in kubernetes Runtime) could be supported -- it's quite constrained on what can be in those `interface{}` values, but it would probably require custom copy logic.

What do you think?

Context: http://github.com/GoogleCloudPlatform/k8s-cluster-bundle

**Comment by lavalamp** [comment]
[API reviewer hat] Don't design your API like that if at all possible, it loses type safety and will just generally be a huge pain. I assume it's not possible, so...

[Kubernetes reviewer hat] What you are trying to do is a solved problem in the k8s codebase, look at "RawExtension".

[gengo/deepcopy-gen reviewer hat] Just manually implement deepcopy for the type, then you don't need this change.

[gengo/deepcopy-gen reviewer hat 2] If you still want to make this change, the code should first test to see if the interface value implements the copy interface, but if it doesn't, then what? What if it doesn't happen to be a copyable thing at all?

**Comment by Kashomon** [comment]
Can be closed.

**Comment by Kashomon** [comment]
For posterity, either RawExtension or unstructured.Unstructured work fine for this usecase.

**Comment by sttts** [comment]
Alias interface and generate a `DeepCopy<interface-name>` func. That's used in different places in Kubernetes. Compare the interface `RuleOwnwer` (https://github.com/kubernetes/kubernetes/blob/9fd23b217800a312a45dbaedb70f4ffa65ec661b/pkg/registry/rbac/reconciliation/reconcile_role.go#L75) and how a deepcopy is generated for that https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/registry/rbac/reconciliation/clusterrole_interfaces.go#L27.
