### ISSUE TITLE
deepcopy-gen generates invalid code for interface{}

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes/gengo#138]
Declaring a `map[string]interface{}` member in a struct handled by deepcopy-gen generates invalid code.
It seems there could be two options available:

* for `map[string]interface{}`, generate code that leverages `runtime.DeepCopyJSON`
* for any `interface{}`, error out instead of generating code that does not compile.

Related issues: #128, https://github.com/kubernetes-sigs/kubebuilder/issues/528 and https://github.com/kubernetes-sigs/controller-tools/pull/126

### Example

* `foo.go`

```golang
// +k8s:deepcopy-gen=true
type Foo struct {
  Data map[string]interface{}
}
```

* `zz_generated.deepcopy.go` (`DeepCopy` function omitted for clarity as it basically calls `DeepCopyInto`)

```golang
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Foo) DeepCopyInto(out *Foo) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]interface{}, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				// INVALID FUNCTION NAME
				(*out)[key] = val.DeepCopyinterface{}()
			}
		}
	}
	return
}
```

**Comment by sttts** [comment]
Please give an example of the code which is wrong now.

**Comment by j-vizcaino** [comment]
@sttts Updated the issue description with an example.

**Comment by sttts** [comment]
It's kind of intentional, though I agree we should show an error in deepcopy-gen instead of `DeepCopyinterface{}` (PR welcome)

In the case of named interfaces, the code is correct:
```
func (in *Foo) DeepCopyInto(out *Foo) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]interface{}, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				// INVALID FUNCTION NAME
				(*out)[key] = val.DeepCopyNamedInterface()
			}
		}
	}
	return
}
```

Use `// +k8s:deepcopy-gen:interfaces=<package-path>.NamedIntrerface` to implement `DeepCopyNamedInterface`.

**Comment by j-vizcaino** [comment]
Yes, for named type this works properly (otherwise nothing would work, I presume 🤔).

This issue is more about deepcopy-gen generating invalid code without erroring out immediately. As is it often used with go generate directives, this has the nasty effect of generating compile errors the user faces later on. Understanding the compile error is less obvious than a straighforward error at generate time. I'll see if I can squeeze some time to submit a PR for this.

How about relying on `runtime.DeepCopyJSON` when the member type is detected as `map[string]interface{}`? To my limited understanding of `runtime.Object`, I felt those where meant to live in the `etcd` storage, meaning they had to be support marshalling and unmarshalling from JSON anyway? (maybe not true if protobuf becomes the only serialisation format?)

**Comment by sttts** [comment]
No, we can't switch to JSON. That's just a special case which is wrong most of the times.

For embedded objects, you should use `runtime.RawExtension`. For general JSON, you can follow https://github.com/kubernetes/kubernetes/blob/d0c3b708026f681f7467d36dcf9696f89ccfcfab/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go#L62. Both is supported with deepcopy-gen.

Giving good hints to the user is more a job for a linter, isn't it? If `map[string]interface{}` is used, this linter could tell the user that `RawExtension` or `JSON` is the better solution.

**Comment by j-vizcaino** [comment]
Thanks for the pointers! 🙇 

Unfortunately, from what I could gather:

* `RawExtension` enforces to follow the same MetaObject base fields (kind, apiVersion, ...) which is clearly too strict and verbose for my use-case.
* `JSON` basically embeds a JSON encoded blob inside a field (maybe I got that wrong). Again, this is impractical for my use-case where I need a free-form object to be provided by the user in the custom resource.

I won't go into too much details here since this is getting out of scope with the current issue. Happy to provide those in a separate issue if you want.

> Giving good hints to the user is more a job for a linter, isn't it? If map[string]interface{} is used, this linter could tell the user that RawExtension or JSON is the better solution.

Not sure what you meant here. My point was that, whether it is considered best practice or not, the generator should not output code that does not compile.

**Comment by sttts** [comment]
> free-form object to be provided by the user in the custom resource.

this is what `JSON` is about.

**Comment by sttts** [comment]
> the generator should not output code that does not compile.

Totally agree. PR welcome to fix that :)

**Comment by j-vizcaino** [comment]
@sttts Is this good to close? (considering #140 is now merged)

**Comment by aybansal-sudo** [comment]
@j-vizcaino I have a similar use case, where we need to implement a arbitrary json in the cr spec. can you please share how you were able to implement this?

**Comment by pcj** [comment]
Leaving a note here for someone in the future, possibly myself.  In our case we are using `github.com/a-h/generate v0.0.0-20220105161013-96c14dfdfb60` to produce `types_generated.go` from `.jschema` files.  In various cases this creates `map[string]interface{}` types, which as per discussion above, is not compatible with deepcopy-gen.  We sed-replaced that and used apiextensionsv1.JSON struct instead.

```
$(generated-types): apis/%/types_generated.go: bin/schema-generate
	@echo "+ Generating API types in $@"
	bin/schema-generate -p $* -o $@ $(SCHEMA_DIR)/*.jschema

	@sed -i.tmp \
		-e 's/map[][]string[][]interface{}/apiextensionsv1.JSON/g' \
		$@

	# NOTE: deepcopy-gen refuses to implement map[string]interface{}.  So, we sed-replaced
	# that above to v1.JSON, and here inserting the import statement that goes along with 
	# it.
	awk 'NR==21{print "apiextensionsv1 \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1\""}1' $@ > $@.tmp
	@mv $@{.tmp,}

	@gofmt -w $@
```

Before:

```go
// Parameters
type Parameters map[string]interface{}
```

After:

```go
// Parameters
type Parameters apiextensionsv1.JSON
```
