### ISSUE TITLE
Update for go modules

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/gengo#143]
Let's begin publishing the module file.

Let's version this thing and start respecting the semver guarantees.

**Comment by lavalamp** [comment]
I'd like to tag v1.0.0 after merging #144. Any objections? I think this commits us to not breaking go interfaces. @sttts @thockin

**Comment by liggitt** [comment]
I think we need a tool to tell us if we're breaking go interfaces or we'll fail at manual inspection/enforcement

I assume this applies not only to the code in this repo but also to the code generated by what is in this repo?

Is the plan to use semantic import tagging for v2 and up?

**Comment by lavalamp** [comment]
good point, I thought I heard something about the go team providing such a tool?

I guess we should also not break the code the samples generate. Maybe we should put the samples in different modules. If we check in the generated code, we could use the above tool to verify this.

> Is the plan to use semantic import tagging for v2 and up?

I am not sure I understand this question, I thought for v2 we actually have to have a v2 in the path, but for v1 we shouldn't. I wasn't planning on thinking about this until someone wants to break the interface :)

**Comment by liggitt** [comment]
> I thought I heard something about the go team providing such a tool?

https://github.com/golang/go/tree/master/api was all I found, but it seems hard-coded to golang src, so would require forking to use against something else

> I am not sure I understand this question, I thought for v2 we actually have to have a v2 in the path, but for v1 we shouldn't.

correct

> I wasn't planning on thinking about this until someone wants to break the interface :)

fair

**Comment by liggitt** [comment]
> good point, I thought I heard something about the go team providing such a tool?

I also saw https://github.com/smola/gocompat mentioned (https://github.com/kubernetes/client-go/issues/234#issuecomment-445785653), but ran into issues trying to run it on our repos

**Comment by liggitt** [comment]
I think https://github.com/golang/tools/tree/master/internal/apidiff is the tool in the works from the go team

**Comment by maelvls** [comment]
a
