### ISSUE TITLE
proposal:  deepequal code generation

### ISSUE THREAD

**Issue by alegacy** [kubernetes/gengo#145]
Hi,
While working on a project I had a need for a "DeepEqual" method that handled some usecases specific to our application that reflect.DeepEqual does not handle.   I was wondering if there is any interest in me contributing this as a code generator along side the deepcopy-gen example that is provided in this repo or if there is any objection to splitting this off into a separate non-Kubernetes repo?  

The two special cases that we needed handled are as follows.  Both are off by default unless a special struct comment tag is supplied by the user:

1) We needed slices to be compared such that order is unimportant.  That is, two slices containing the same elements but in different order would report as equal.  This is contrary to how reflect.DeepEqual works.   I can see this being useful to other people as it is not always convenient to keep a slice in sorted order when adding/removing from it, or to want to sort it before comparing.

The type would be tagged like this to enable this special this handling:

```golang
// +k8s:deepequal-gen:unordered-array=true
type MyList []string
```

2) We needed to handle a special usecase for struct comparisons whereby nil fields on the left hand side (the receiver) of the comparison would be ignored and assumed to be equal regardless of the value on the right hand side (the input).   The reason for this is that we have a need to express certain fields as optional features and if the struct on the right has it set then we just treat that an acceptable value.  For example,  consider this struct.

```golang
// +k8s:deepequal-gen:ignore-nil-fields=true
type MyStruct struct {
    Name string `json:"name"`
    Address string `json:"address"`
    Age *int `json:"age,omitempty"`
}

a := MyStruct{Name: "John", Address: "Somewhere"}
ageB := 30
b := MyStruct{Name: "John", Address: "Somewhere", Age: &ageB}
ageC := 31
c := MyStruct{Name: "John", Address: "Somewhere", Age: &ageC}

a.DeepEqual(&b) == true
b.DeepEqual(&c) == false
```

I admit that this particular behavior may not be applicable to many users, but having this available as part of the code generator was a time saver as we have many structures and many of those have these optional fields that we needed to handle in this way.

If there is interest I can augment the unit tests and prepare a PR.

**Comment by sttts** [comment]
Have you checked those deep comparison libraries like https://github.com/google/go-cmp ?

**Comment by sttts** [comment]
Also note the discussion around semantic comparison in https://github.com/kubernetes/utils/pull/83.

**Comment by alegacy** [comment]
@sttts Thanks.  Yes, I had considered go-cmp, but found that since we would need to provide custom Equal() methods for most of our structs, go-cmp became nothing more than a framework to traverse the nested structures with us providing all of the actual Equal logic by hand.   I guess we could change the code generator to emit Equal() methods rather than DeepEqual() methods and only for those fields that are tagged.   That way we'd be able to leverage go-cmp but either way we would be writing a code generator so I figured why not go all the way.  

Also, I couldn't find a way to do a generate slice sorter transformer.  It seemed like we'd have to provide a custom method for each unique list type.  So, again, it seemed like more unnecessary manual coding.

**Comment by sttts** [comment]
Just start with deepcopy as the basis, duplicate the generator and make it create DeepEqual. Woulnd't mix those two though.

**Comment by alegacy** [comment]
@sttts thanks.  That is the approached that I used.  I used deepcopy as a guide/template and built the deepequal generator around that.  So based on the other threads you mentioned I take it there is no interest in this functionality for any Kubernetes projects.  I agree that go-cmp is a better approach if no custom behavior is needed.  

Since this deepequal-gen generator is inspired by the deepcopy-gen code are there any objections to using this as a basis for deepequal-gen and having it live on completely separate from Kubernetes?  I will provide comments/documentation pointing back to deepcopy-gen as the original source inspiration.

**Comment by sttts** [comment]
@alegacy I wouldn't say that there is no interest. For Kubernetes I would be very interested how the generated code compares to `reflect.DeepEqual` performance-wise, and whether we have some critical code-pathes which would make this interesting.

Just put it out there in some `deepequal-gen` Github project.

**Comment by alegacy** [comment]
@sttts Ok, thanks for your feedback.  I will clean it up and add more unit tests and get it posted to a separate repo and provide the link here.

**Comment by lavalamp** [comment]
Yup, a separate repo sounds like the best place--gengo should be obeying go versioning rules and not make breaking changes to its interfaces. 👍

**Comment by luisdavim** [comment]
I think adding something like https://github.com/Wind-River/deepequal-gen to the `gengo` (this) repo would make sense....
