### ISSUE TITLE
pkg/parser: Parses too much stuff, eventually goes into stdlib reflect, rune etc.

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/gengo#149]
I'm author of https://github.com/ahmetb/gen-crd-api-reference-docs/ which is a tool to generate API reference docs for most kubernetes CRD projects (e.g. usually built with kubebuilder). I use `gengo/parser` package.

Recently it started to break because its parsing goes waaaay too deep.

It's parsing this `k8s.io/apimachinery/pkg/runtime.Scheme` type: https://sourcegraph.com/github.com/knative/serving@07437021afd54ecd391f84e66616751108bc6644/-/blob/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go#L47:6

This Scheme has **unexported** fields like `gvkToType map[schema.GroupVersionKind]reflect.Type` which refer to `reflect.Type`.

So gengo/parser goes and parses reflect.Type, which ends up going muuuuch deeper and ends up parsing types like `rune` builtin as `Unsupported` kind.

Eventually my program bursts out with `Type{Name: "invalid type", Kind: Unsupported, Package: ""}` which isn't great.

Would it be possible to change gengo/parser so that

- it doesn't parse lowercase (unexported) fields
- it doesn't parse stdlib runtime.* package

I think these two improvements would help massively.

**Comment by lavalamp** [comment]
An option to not descend on unexported fields makes sense to me.

**Comment by ahmetb** [comment]
I've added that. Sadly it actually didn't make a difference.
I'm getting types with Name=`invalid type` from this package.
It seems that something with the handling of embedded types has changed. I'll try to investigate further and report back what's going wrong soon.
