### ISSUE TITLE
Generating non-go code

### ISSUE THREAD

**Issue by nicolaferraro** [kubernetes/gengo#158]
Hi, I'm looking into using gengo for generating ".adoc" files from go code.

Is it a valid use case? I see everything is built around code.

**Comment by lavalamp** [comment]
Yes; since you write the generator, you can make it generate anything you like. I believe the kubernetes code base uses this to generate .proto files, so you can look for that for an example.

**Comment by nicolaferraro** [comment]
Thanks @lavalamp!
