### ISSUE TITLE
Gengo passes file path as package path to build.Context.Import(). 

### ISSUE THREAD

**Issue by al45tair** [kubernetes/gengo#166]
In parse.go, the function `Builder.importWithMode()` calls `build.Context.Import()` with `dir` as the first argument. But `dir` is a _filesystem path_, as opposed to a package path, and `Import` expects _a package path_ as its first argument.

On UNIX systems, this doesn't matter because the two turn out to be the same thing. On Windows, it is a huge problem because package paths are _always_ slash separated while filesystem paths use backslashes.

**Comment by sttts** [comment]
I remember that somebody build Windows CI some time ago. Isn't that running anymore?
