### ISSUE TITLE
`k8s:deepcopy-gen` does not work when a struct has comments

### ISSUE THREAD

**Issue by pedro823** [kubernetes/gengo#168]
The deepcopy generator cannot consider more than one line of comments
before the actual structure.

A part of my code was this:
```go
import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:deepcopy-gen=true

// SkinnyPod is a stripped down version of k8s' Pod structure.
// By keeping only the parts we use from the pod in memory,
// we reduce the memory footprint of the application.
type SkinnyPod struct {
	metav1.ObjectMeta
	Spec   corev1.PodSpec
	Status corev1.PodStatus
}
```

Running the kubernetes generator, I had this error:

```
F0204 10:23:39.567087   91737 deepcopy.go:183] Type <redacted>/internal/types.SkinnyObject requests deepcopy generation but is not copyable
```

The error's stack pointed out to this line of code: <https://github.com/kubernetes/gengo/blob/1e9b17e831be2da1e1781acc7a0d8588aaf622b3/examples/deepcopy-gen/generators/deepcopy.go#L183>.

After reading the code, It made sense just to remove the comments from the `struct` and try again. It did work like this:
```go
import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:deepcopy-gen=true

type SkinnyPod struct {
	metav1.ObjectMeta
	Spec   corev1.PodSpec
	Status corev1.PodStatus
}
```

**Comment by sttts** [comment]
The error message`Type <redacted>/internal/types.SkinnyObject requests deepcopy generation but is not copyable` talks about SkinnyObject, but your example is `SkinnyPod`. Wrong copy&paste?

**Comment by sttts** [comment]
`extractEnabledTypeTag` is considering `comments := append(append([]string{}, t.SecondClosestCommentLines...), t.CommentLines...)`. So two blocks of comments should work.

**Comment by pedro823** [comment]
I can't confirm for now, but i think it tried to generate the deep copier for a interface that was declared in the same file but was moved... Maybe the file wasn't updated. 

I cannot reproduce the problem anymore, so I'm closing the issue 😕
