### ISSUE TITLE
Capture the underlying value of constants.

### ISSUE THREAD

**Issue by jpeach** [kubernetes/gengo#187]
When using gengo to generate API documentation, it would be pretty convenient to be able to get the underlying [value](https://godoc.org/go/types#Const.Val) of the constant. This could be used to generate documentation for the acceptable values of an enum.

**Comment by lavalamp** [comment]
I agree that this sounds useful and not too hard.

**Comment by jpeach** [comment]
> I agree that this sounds useful and not too hard.

@lavalamp Are you able to review #188?
