### ISSUE TITLE
Any way to get anonymous variables? (blank identifier)

### ISSUE THREAD

**Issue by andersfylling** [kubernetes/gengo#194]
I like generating some basic implementation for types. And I link these using a compile time check:
```go
var _ DeepCopier = (*SomeTypeOfMine)(nil)
```

Using the parser builder, I was not able to get such variables.

**Comment by lavalamp** [comment]
I don't think those are parsed/stored currently. I'm not opposed to adding them. However I don't think it'll be a high priority for me/us, thanks for understanding.
