### ISSUE TITLE
package k8s.io/gengo: no Go files in /Users/like/gomod/src/k8s.io/gengo

### ISSUE THREAD

**Issue by likenamehaojie** [kubernetes/gengo#197]
when i use   go get k8s.io/gengo to install gengo 

go get k8s.io/gengo
package k8s.io/gengo: no Go files in /Users/like/gomod/src/k8s.io/gengo

**Comment by likenamehaojie** [comment]
platform:MacOS
@gnufied @ncdc @rphillips @mml

**Comment by nikhita** [comment]
@likenamehaojie `go get k8s.io/gengo/...` should work

**Comment by nikhita** [comment]
Looks like the README has slightly incorrect instructions. Created https://github.com/kubernetes/gengo/pull/198 :)
