### ISSUE TITLE
The `bounding-dirs` flag of the `deepcopy-gen` has no effect

### ISSUE THREAD

**Issue by Iceber** [kubernetes/gengo#209]
Since https://github.com/kubernetes/gengo/pull/110 and https://github.com/kubernetes/gengo/pull/32 remove calls to [`copyableAndInBounds`](https://github.com/kubernetes/gengo/blob/485abfe95c7c792c41929dea3578927f90485a9f/examples/deepcopy-gen/generators/deepcopy.go#L279), the `bound dirs` is not checked.

@sttts @thockin Is this a bug? Or is the `bound-dirs` flag not going to be supported?

**Comment by sttts** [comment]
After so much time where `bound-dirs` is broken, I would call it unsupported. I don't think there is any objection to fix it if somebody finds time for it. It doesn't matter in the kube code base today.

**Comment by Iceber** [comment]
Now that `bounding-dirs` is broken, I'm going to remove this flag from the [`code-generate/generate-groups.sh`](https://github.com/kubernetes/code-generator/blob/48d3d44c66d61e1a6cf0bd5bd1ecf94c3e46a270/generate-groups.sh#L74) to avoid the illusion that this falg is working.

@sttts What do you think?
