### ISSUE TITLE
Copyright boilerplate changes YEAR, but shouldn't

### ISSUE THREAD

**Issue by thockin** [kubernetes/gengo#24]
The copyrighted code is either copyright the first year it was generated or else it is copyright the year we wrote gengo.  It obviously doesn't change copyright by nature of being regenerated.

**Comment by thockin** [comment]
Legal guidance is that the year is literally meaningless on these files.  My proposal is that we simply omit the year field, and fix the kubernetes linter(s) to accept boilerplate with or without year.

**Comment by sttts** [comment]
> My proposal is that we simply omit the year field,

:+1:
