### ISSUE TITLE
AddDirRecursive is broken on with go1.20

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/gengo#241]
https://pkg.go.dev/k8s.io/gengo/parser#Builder.AddDirRecursive doesn't work if a path doesn't contain any go code. Prior go1.19 returned `NoGoError` which was handled [here](https://github.com/kubernetes/gengo/blob/ab3349d207d4cc9f4bc5c37ba6aa062b4b2ffacc/parser/parse.go#L159). Now it returns a different error breaking the parser.

See upstream issue: https://github.com/golang/go/issues/58903

Workaround is to create an empty `go` file - ie. `doc.go` at every intermediate level. Maybe gengo parser can just handle the new error type.

**Comment by dprotaso** [comment]
I didn't really understand the response from the `go` team - it seems counter intuitive so I'm poking upstream.

**Comment by thockin** [comment]
I have a branch with MASSSSSSSIVE overhaul to gengo (i.e. gengo/v2)
coming.  I have to look at this new one, but I won't have time today
probably.

Please hold off on major major rework until I can catch up?

**Comment by thockin** [comment]
Cool - this explains a weird behavior I saw just this weekend :)

My branch (hopefully to become gengo/v2) totally overhauls this path (to use `packages.Load`), so it's all moot eventually

**Comment by thockin** [comment]
I'm still working on it, but very slowly.  Is there a specific use-case that is broken right now?

**Comment by dprotaso** [comment]
This broke some crd to docs tools but there's a work around - add an empty go file to the dirs with no code

**Comment by thockin** [comment]
OK.  I'm keeping this in my radar, but the overhaul is not imminent.  If
there's an easy fix, I am open to it.

**Comment by dprotaso** [comment]
> If there's an easy fix, I am open to it.

Switch to ImportDir

https://github.com/kubernetes/gengo/issues/241#issuecomment-1458350539

**Comment by thockin** [comment]
Will be fixed in v2 (https://github.com/kubernetes/gengo/pull/259)

**Comment by dprotaso** [comment]
Woot thanks!
