### ISSUE TITLE
Import-boss should be able to check indirect dependencies

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/gengo#252]
We started looking at the import-boss tool for the cluster-api project. We have a number of API groups across the core project and the providers that implement the cluster-api contracts.
We would like to be able to create clean API groups with few imports to allow them to easily be imported into other projects, without bringing in complex dependencies such as controller-runtime.

We recently ran through and purged the wider dependencies for most of the core APi groups bringing it down to pretty much standard library, core Kube API and apimachinery imports.

We set up import-boss to prevent the re-addition of controller-runtime dependencies but noticed that, it doesn't currently track transitive dependencies. If I add a dependency to the API group that then itself imports something more complex like controller-runtime, this allows me to negate the import-boss.

I would like import-boss to be able to prevent me adding a dependency that matches my forbidden dependencies, but also track that my indirect dependencies don't include a forbidden dependency.

If this is something that would be useful to the wider community/would be accepted if a PR were to be made, I can try to find some time to investigate/implement this as an optional feature for the import-boss rules.

**Comment by alexzielenski** [comment]
xref: semi-related discussion recently
https://github.com/kubernetes/kubernetes/pull/120506#discussion_r1319448865

**Comment by thockin** [comment]
gengo/v2 (https://github.com/kubernetes/gengo/pull/259) moves import-boss to k8s.io/code-generator (https://github.com/kubernetes/kubernetes/pull/122624) and does, in fact, add the option to do transitive deps.

When that lands, please take a look.
