### ISSUE TITLE
How to add generated file back to universe/builder

### ISSUE THREAD

**Issue by tomleb** [kubernetes/gengo#260]
Hi,

I'm trying to speed up `go generate ./...` that's using gengo to generate code. Most time I see is spent re-parsing the exact same files for each generator I'm using:
1. custom generator
2. deepcopy
3. another one

I'd like to keep the same "universe" or builder and just add files/packages to it as I go. I think I got it working correctly by calling `parser.NewBuilder()` once, and then recreating a context for each of those steps. The issue I'm facing now is that the generated code from 1 is not added to the universe so 2 doesn't see it. Both of these are in the same packages so calling `AddDir()` does not work - it assumes it already parsed the package.

Do you know of a solution/workaround for this? I'm not the original developer of these generators so still trying to understand the library.

**Comment by thockin** [comment]
The only real fix is to build them all into a single binary.  If you use gengo/v2 you can call `c.LoadPackages()`
