### ISSUE TITLE
gengo change of behavior with generated import statements

### ISSUE THREAD

**Issue by jpeeler** [kubernetes/gengo#30]
When using gengo in service-catalog, I found that the import statements aren't generated in the same way any more. The change of behavior started after the commit of 7ca94dd123f0f4965aac2e59ef249d8eaef14bcc, which was on Jan 3. I filed a bug https://github.com/kubernetes-incubator/service-catalog/issues/223 showing the difference in behavior.

**Comment by thockin** [comment]
Replied on your bug.

This is not a bug in gengo, I think.  Having it generate paths with `vendor` in them seems wrong.  The resulting change looks like you should need to add `k8s.io/kubernetes` to `--bounding-dirs` on deepcopy

**Comment by jpeeler** [comment]
The committed code above appears to have fixed the problem.
