### ISSUE TITLE
Clarify ownership and merge policy

### ISSUE THREAD

**Issue by sttts** [kubernetes/gengo#63]
After a couple of times with PRs not being merged here for weeks, can we clarify who can approve, lgtm and merge PRs in here? Looking at older PRs neither of these groups match the OWNERS file.

**Comment by thockin** [comment]
Please don't hesitate to ping PRs if they get lost.  This repo has a
relatively small number of people who know it at all.

Wojtek, Clayton, Daniel, and myself, mostly.  And you now :)

**Comment by lavalamp** [comment]
Turns out I wasn't subscribed to the repo. I am now.

**Comment by sttts** [comment]
We have prow enabled here now. So merging is controller with the usual lgtm and approval. So this issue is solved 🎉
