### ISSUE TITLE
Consider decoupling package->directory lookups from $PWD

### ISSUE THREAD

**Issue by jmillikin-stripe** [kubernetes/gengo#64]
Branching discussion from https://github.com/kubernetes/repo-infra/pull/19

Gengo currently assumes that a package `"k8s.io/foo/bar"` can always be found in `${PWD}/k8s.io/foo/bar/`, and becomes very unhappy if the generator program is called from a different directory. This makes its use from Bazel rules complicated, and requires Kubernetes BUILD files to use custom logic such as `go_genrule()` instead of Bazel's built-in `genrule()`.

**Comment by thockin** [comment]
/lifecycle frozen

Can you show a more complete repro case?

**Comment by jmillikin-stripe** [comment]
See `def _compute_genrule_command(ctx):` in the linked patch for a more complete comment, and to see how gengo is being invoked.

Bazel assumes that the build steps it runs are insensitive to the current working directory. For Gengo this isn't true, it expects certain Go packages to be located at particular parts of the filesystem as resolved relative to `$PWD`. As a result, the Kubernetes build scripts need to define their own genrule-like wrapper to set up a Gengo-compliant environment.

(I don't have full context any more since this was filed months ago as a side-effect of some other yak hunt)

**Comment by estroz** [comment]
This directly relates to parsing non-GOPATH repos: https://github.com/kubernetes/gengo/pull/144#issuecomment-480477427

**Comment by thockin** [comment]
Will be fixed in v2 (https://github.com/kubernetes/gengo/pull/259)
