### ISSUE TITLE
Time to version!

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/gengo#78]
Gengo is slow enough moving that I think it's time to call it 1.0.0 and start paying attention to our interface changes.

**Comment by wojtek-t** [comment]
+1

**Comment by thockin** [comment]
Ahh, man, I have so many things I want to fix.

**Comment by lavalamp** [comment]
Me too, I think a bunch of changes have gone in that wouldn't have been my
first choice. But there are only so many hours in the day, and we have to
start somewhere :(

We need a version to put in the `dep` files of things that depend on this.

**Comment by thockin** [comment]
gengo.2 here we come!
