### ISSUE TITLE
master doesn't work with release-1.8 kubernetes/code-generator

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/gengo#81]
kubernetes/code-generator/cmd/client-go  is missing the --go-header and -o flags.  @stts told me the issue was with the version of gengo I was using.

We should have a branch for kubernetes/gengo that matches the code vendored by kubernetes/kubernetes at the same branch.

To get the right version of gengo I need to pin it to a commit in my glide.yaml.  I should be able to pin all kubernetes/* repos to a release-1.* and they should work together.

**Comment by thockin** [comment]
I think we need systemic management of release branches.  I don't know that
we should make all of our repos be the same tags at the same times, though.

**Comment by munnerz** [comment]
I've also just run into this.

Within the code-generator repository, the Godeps.json file *does* point to the correct revision that is compatible, however I'm using dep which seemed to not pick this up.

As a workaround for dep (given it's 'gradually' becoming a standard Go tool), we can write some tooling to generate a Gopkg.toml file that pins to the appropriate revision, but this isn't really a scalable solution for all tools as we'd then need a glide.lock or some equivalent too, and we'll also need to pin to specific revisions of a lot of the k8s repositories (as opposed to a release branch, or a range of versions).

It'd be great if gengo could be versioned in *some way*. Right now the only way I get apimachinery, client-go etc to work is by pinning each to `release-1.8` in my own Gopkg.toml. Even if we did tag gengo and pin to a specific revision, we need *some way* to have that requirement be picked up by each dependency management tool, which I don't think is particularly easy. If we are using `release-1.8` etc even in gengo, then it will at least be more intuitive from a developer perspective (the rule becomes `all k8s.io/* repos should be pinned to the same release branch`)

**Comment by sttts** [comment]
> we need some way to have that requirement be picked up by each dependency management tool, which I don't think is particularly easy

We cannot solve this problem in gengo. We have Godeps.json in each project and they are the only truth. We can add another Gopkg.toml for dep beside it (hopefully soon). But the fact that master of gengo is incompatible with a release branch of kube is not an issue of gengo. We should close this issue for that reason.
