### ISSUE TITLE
deepcopy-gen doesn't work on Windows

### ISSUE THREAD

**Issue by ricky26** [kubernetes/gengo#83]
There are a couple of bugs which stop deepcopy-gen from working on Windows:
- `golangTrackerLocalName` uses the path separator to split package names, but package names can contain forward-slashes as well (I'm not actually sure whether the package names which reach this function can actually contain back-slashes). I worked around this locally by using a split on either forward- or back-slashes.
- In parser/parse.go: `strings.HasSuffix(f.name, "/doc.go")`. I just hacked this locally to have an `|| strings.HasSuffix(f.name, "\doc.go")`, it seems like this one probably *should* be using path separator.

I can put together a PR if anyone has any rough suggestions about how to fix these more properly (I am not a Go expert).

**Comment by thockin** [comment]
On Fri, Nov 10, 2017 at 4:33 AM, Ricky Taylor <notifications@github.com> wrote:
>
> There are a couple of bugs which stop deepcopy-gen from working on Windows:
>
> golangTrackerLocalName uses the path separator to split package names, but package names can contain forward-slashes as well (I'm not actually sure whether the package names which reach this function can actually contain back-slashes). I worked around this locally by using a split on either forward- or back-slashes.

Does Go specify forward slashes or does it not care?  It seems 100%
wrong to allow imports to use either form, because "foo\bar" on linux
means something TOTALLY different.  I can't find anything in the
laguage spec.  We may want to see clarity from go team.

> In parser/parse.go: strings.HasSuffix(f.name, "/doc.go"). I just hacked this locally to have an || strings.HasSuffix(f.name, "\doc.go"), it seems like this one probably should be using path separator.

We should do a path.Split and check the filename instead, right?

> I can put together a PR if anyone has any rough suggestions about how to fix these more properly (I am not a Go expert).

Great!  I think we should ask Go people if `import
"github.com\foo\bar" is supposed to work or if it must be
"github.com/foo/bar" - if we take input in native form, we probably
need a canonicalize() function to convert.

**Comment by thockin** [comment]
I just asked on golang-nuts

**Comment by thockin** [comment]
pinged golang-nuts again - no reply before

**Comment by thockin** [comment]
From Ian Lance Taylor:

The language spec says that an implementation is permitted but not
required to forbid the backslash character in an import path
(https://golang.org/ref/spec#Import_declarations).  The gc compiler
does in fact refuse to accept a backslash character in an import path.
So in practice you need to use forward slashes.

So we should only accept/emit forward slashes in import paths, I guess.

**Comment by ricky26** [comment]
Cool, I'm still happy to have a go at whipping up a PR with those two changes in (splitting on forward slash for import paths read and using path.Split to detect doc.go). I lost track of this issue for a while since I'd hacked it locally.

Perhaps I could make it warn or error if import paths contain a backslash? At least that way if someone hits it they will know why it's not working.

**Comment by ricky26** [comment]
I've opened a PR for this now at #101.

**Comment by ricky26** [comment]
PR #101 has been merged, this can now be closed.
